# If this already exists, we can either use a data block or import it. 
# terraform import zedcloud_datastore.Private_HTTP_Server_on_8080 ...UUID... 
resource "zedcloud_datastore" "Private_HTTP_Server_on_8080" {
  name  = "Private_HTTP_Server_on_8080"
  title = "Private_HTTP_Server_on_8080"

  ds_type = "DATASTORE_TYPE_HTTP"
  ds_fqdn = "http://192.168.192.168:8080"
  ds_path = "images_datastore"

  # Invalid option for HTTP/HTTPS datastores.
  # api_key  = "DEADBEAFCAFE1234567890"
}

# # Needed to retrieve the ID which is generated by Zedcloud.
# data "zedcloud_datastore" "Local-HTTP-Server-8080" {
#   name  = zedcloud_datastore.Local-HTTP-Server-8080.name
#   title = zedcloud_datastore.Local-HTTP-Server-8080.title
# 
#   ds_type = zedcloud_datastore.Local-HTTP-Server-8080.ds_type
#   ds_fqdn = zedcloud_datastore.Local-HTTP-Server-8080.ds_fqdn
# }
